name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Merge pull request
      if: github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'development' && github.event.pull_request.mergeable
      uses: actions-ecosystem/action-merge-pull-request@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pull_request_number: ${{ github.event.pull_request.number }}